import type { NextPage } from "next";
import Head from "next/head";
import { Box } from "../src/components/box";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.header}>
          <h1 className={styles.upperHeader + " " + "dark-blue"}>
            Reliable, efficient delivery
          </h1>
          <h1 className={styles.lowerHeader + " " + "dark-blue"}>
            Powered by Technology
          </h1>
          <p className="gray-blue">
            Our Artificial intelligence powered tools use millions of project
            data points to ensure that your project in successful
          </p>
        </header>
        <section className={styles.box}>
          <div className={styles.grid1}>
            <Box
              title="Supervisor"
              description="Monitors activity to identify project roadblocks"
              image="/images/icon-supervisor.svg"
              bgColor="bg-cyan"
            />
          </div>
          <div className={styles.grid2}>
            <Box
              title="Team Builder"
              description="Scans our talent network to create the optimal team for your project"
              image="/images/icon-team-builder.svg"
              bgColor="bg-red"
            />
          </div>
          <div className={styles.grid3}>
            <Box
              title="Karma"
              description="Regularly evaluates our talent to ensure quality"
              image="/images/icon-karma.svg"
              bgColor="bg-orange"
            />
          </div>
          <div className={styles.grid4}>
            <Box
              title="Calculator"
              description="Uses data from past projects to provide better delivery estimates"
              image="/images/icon-calculator.svg"
              bgColor="bg-blue"
            />
          </div>
        </section>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
